# Generated by Django 6.1.1 on 2026-09-22 02:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgoraProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(help_text='Your public name in The Agora (letters, numbers, hyphens, underscores).', max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Handle may only contain letters, numbers, hyphens, and underscores.', regex='^[\\w-]+$')])),
                ('about_me', models.TextField(blank=True, default='', max_length=1000)),
                ('favorite_movie', models.CharField(blank=True, default='', max_length=128)),
                ('favorite_song', models.CharField(blank=True, default='', max_length=128)),
                ('favorite_artist', models.CharField(blank=True, default='', max_length=128)),
                ('quote', models.TextField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agora_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'agora profile',
                'verbose_name_plural': 'agora profiles',
            },
        ),
    ]
