# Generated by Django 6.1.1 on 2026-09-22 02:43

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeutrinoKey', '0002_add_user_keypair'),
        ('agora', '0001_initial_profile_category'),
        ('organizer', '0003_add_folder_fk_to_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=32, unique=True)),
                ('title', models.CharField(default='Bruh, Change the Title', max_length=64)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('secure_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('result_nonce_text', models.CharField(default=b'AAAANw==', max_length=128)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='agora.agoraprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='agora.category')),
                ('data_dek', models.ManyToManyField(default=1, related_name='agora_topic_dek', to='NeutrinoKey.dek')),
                ('data_kek', models.ManyToManyField(default=1, related_name='agora_topic_kek', to='NeutrinoKey.kek')),
                ('tags', models.ManyToManyField(blank=True, related_name='agora_topics', to='organizer.tag')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=32, unique=True)),
                ('title', models.CharField(default='Bruh, Change the Title', max_length=64)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('secure_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('result_nonce_text', models.CharField(default=b'AAAANw==', max_length=128)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='agora.agoraprofile')),
                ('data_dek', models.ManyToManyField(default=1, related_name='agora_reply_dek', to='NeutrinoKey.dek')),
                ('data_kek', models.ManyToManyField(default=1, related_name='agora_reply_kek', to='NeutrinoKey.kek')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='agora.reply')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='agora.topic')),
            ],
            options={
                'verbose_name': 'reply',
                'verbose_name_plural': 'replies',
                'ordering': ['pub_date'],
            },
        ),
    ]
