# Generated by Django 6.1.1 on 2026-09-22 02:47

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model('agora', 'Category')
    categories = [
        (
            'Discussion Boards',
            'discussion-boards',
            'Open discourse on any topic — share ideas, ask questions, start conversations.',
        ),
        (
            'Creative Showcase',
            'creative-showcase',
            'Share your creative works — art, writing, music, and more — with the community.',
        ),
        (
            'Collaborative Projects',
            'collaborative-projects',
            'Find collaborators, share progress, and build together.',
        ),
        (
            'Knowledge Exchange',
            'knowledge-exchange',
            'Tutorials, Q&A, peer learning — teach what you know, learn what you don\'t.',
        ),
    ]
    for name, slug, description in categories:
        Category.objects.get_or_create(
            slug=slug,
            defaults={'name': name, 'description': description},
        )


def remove_categories(apps, schema_editor):
    Category = apps.get_model('agora', 'Category')
    Category.objects.filter(slug__in=[
        'discussion-boards',
        'creative-showcase',
        'collaborative-projects',
        'knowledge-exchange',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0002_add_topic_reply'),
    ]

    operations = [
        migrations.RunPython(seed_categories, remove_categories),
    ]
