# Generated by Django 6.1.1 on 2026-09-20 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeutrinoKey', '0002_add_user_keypair'),
        ('organizer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('dek_nonce', models.CharField(help_text='Base64-encoded nonce for this folder DEK', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dek', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folders', to='NeutrinoKey.dek')),
                ('kek', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folders', to='NeutrinoKey.kek')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizer.userfolder')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'parent', 'name')},
            },
        ),
    ]
