# Generated by Django 6.1.1 on 2026-09-20 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_add_user_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_files', to='organizer.userfolder'),
        ),
        migrations.AddField(
            model_name='miscfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_files', to='organizer.userfolder'),
        ),
        migrations.AddField(
            model_name='musicfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_files', to='organizer.userfolder'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_files', to='organizer.userfolder'),
        ),
    ]
