# Generated by Django 6.1.1 on 2026-09-19 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeutrinoKey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AESKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BinaryField()),
                ('salt', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='RSAKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.BinaryField()),
                ('public_key', models.BinaryField()),
                ('wrapped_private_key', models.BinaryField()),
                ('wrapped_public_key', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='UserKeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key_pem', models.TextField(help_text='RSA-4096 public key in PEM format (cleartext)')),
                ('encrypted_private_key', models.BinaryField(help_text='RSA-4096 private key encrypted with AES-256-EAX')),
                ('private_key_nonce', models.CharField(help_text='Base64-encoded AES-EAX nonce for private key encryption', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dek', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_keypairs', to='NeutrinoKey.dek')),
                ('kek', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_keypairs', to='NeutrinoKey.kek')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keypair', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user key pair',
                'verbose_name_plural': 'user key pairs',
            },
        ),
    ]
